name: sys-frontend-app
static_sites:
  - name: sys-frontend-develop
    github:
      repo: MDEIS-V2E4/sys-frontend
      branch: develop
    build_command: npm install && npm run build
    output_dir: dist
    envs:
      - key: VITE_BASE_URL
        value: https://sys-backend-develop.ondigitalocean.app/v1

  - name: sys-frontend-stage
    github:
      repo: MDEIS-V2E4/sys-frontend
      branch: stage
    build_command: npm install && npm run build
    output_dir: dist
    envs:
      - key: VITE_BASE_URL
        value: https://sys-backend-stage.ondigitalocean.app/v1

  - name: sys-frontend-prod
    github:
      repo: MDEIS-V2E4/sys-frontend
      branch: master
    build_command: npm install && npm run build
    output_dir: dist
    envs:
      - key: VITE_BASE_URL
        value: https://sys-backend-prod.ondigitalocean.app/v1


# name: sys-frontend-app
# services:
#   - name: sys-frontend
#     image:
#       registry_type: DOCR
#       registry: dev-registry-2025
#       repository: sys-frontend
#       tag: TAG_PLACEHOLDER
#       # deploy_on_push:
#       #   enabled: true
#     envs:
#       - key: VITE_BASE_URL
#         value: https://sys-backend-app-krqjr.ondigitalocean.app/v1
