name: sys-frontend-app

static_sites:
  - name: sys-frontend
    github:
      branch: main
      repo: usuario/sys-frontend  # Cambia esto con tu repo real
    envs:
      - key: VITE_BASE_URL
        value: https://sys-backend-app-krqjr.ondigitalocean.app/v1
    build_command: npm run build
    output_dir: dist
