name: Deploy to local environment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Start Vite server in production mode
      shell: powershell
      run: |
        start /B cmd /c "npm run preview -- --port 3000"
        timeout /t 5

      # run: npm run start &    para linux
