name: Deploy to local environment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Start Vite server in production mode
      shell: pwsh
      run: |
        Start-Job -ScriptBlock { npm run start }
        Start-Sleep -Seconds 5

      # run: npm run start &    para linux
